<script lang="ts">
	const currentYear = new Date().getFullYear();
</script>

<footer class="bg-trend-dark text-white mt-auto">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
		<div class="flex flex-col md:flex-row items-center justify-between gap-4">
			<div class="flex items-center gap-3">
				<img
					src="/assets/logo.webp"
					alt="AATF Logo"
					class="w-8 h-8 rounded-full"
				/>
				<div>
					<p class="font-medium">AATF AI News Aggregator</p>
					<p class="text-sm text-trend-gray-400">
						Powered by Claude Opus 4.5
					</p>
				</div>
			</div>

			<div class="flex items-center gap-6 text-sm text-trend-gray-400">
				<span>AATF - AI Acceleration Task Force</span>
				<span>&copy; {currentYear}</span>
				<a href="/about" class="hover:text-white transition-colors">[About]</a>
				<a href="/feeds" class="hover:text-white transition-colors">[RSS]</a>
			</div>
		</div>

		<!-- AI Disclaimer -->
		<div class="border-t border-trend-gray-700 mt-4 pt-4">
			<p class="text-xs text-trend-gray-500 text-center">
				Content generated by AI. May contain errors.
				<a href="/about" class="hover:text-trend-gray-400 underline">Learn more</a>
			</p>
		</div>
	</div>
</footer>
